apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
    nodePort: 30000
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: backend-deployment

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: backend-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: backend-deployment
    spec:
      containers:
      - name: backend-deployment
        image: sunnytarawade/django-app:3 
        ports:
        - containerPort: 8000
        env:
          - name: DEBUG
            valueFrom:
              configMapKeyRef:
                name:  gsoc-dev-config-map
                key: debug
          - name: REDIS_HOST
            valueFrom:
              configMapKeyRef:
                name:  gsoc-dev-config-map
                key: redis-host
          - name: REDIS_PORT
            valueFrom:
              configMapKeyRef:
                name:  gsoc-dev-config-map
                key: redis-port
          - name: AMQP_HOST
            valueFrom:
              configMapKeyRef:
                name:  gsoc-dev-config-map
                key: amqp-host
          - name: AMQP_PORT
            valueFrom:
              configMapKeyRef:
                name:  gsoc-dev-config-map
                key: amqp-port

          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: gsoc-dev-secret
                key: secret-key

          - name: ELASTICSEARCH_HOST
            valueFrom:
              secretKeyRef:
                name: gsoc-dev-secret
                key: es-host
          - name: ELASTICSEARCH_PORT
            valueFrom:
              secretKeyRef:
                name: gsoc-dev-secret
                key: es-port
          - name: ELASTICSEARCH_USER
            valueFrom:
              secretKeyRef:
                name: gsoc-dev-secret
                key: es-user
          - name: ELASTICSEARCH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: gsoc-dev-secret
                key: es-password
